version: '3.8'
services:
  app:
    image: ${ODOO_IMAGE:-odoo}:${ODOO_TAG:-18}
    container_name: ${ODOO_CONTAINER:-odoo}
    user: root
    depends_on:
      - db
    ports:
      - ${ODOO_PORT:-8069}:8069
    # - "${ODOO_CHAT_PORT:-8072}:8072"
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=${PG_USER:-changeme}
      - PASSWORD=${PG_PASS:-password}
    volumes:
      - ${ENTRYPOINT:-./entrypoint.sh}:/entrypoint.sh   # use for install additional package (Optional)
      - ${ODOO_ADDONS:-./addons}:/mnt/extra-addons
      - ${ODOO_CONFIG:-./etc}:/etc/odoo
      - ${ODOO_BACKUP:-./backup/ce}:/etc/odoo/backup
    restart: always  
  db:
    image: postgres:16
    user: root
    container_name: ${COMPOSE_PROJECT_NAME:-odoo}-db
    environment:
      - POSTGRES_USER=${PG_USER:-changeme}
      - POSTGRES_PASSWORD=${PG_PASS:-password}
      - POSTGRES_DB=postgres
    ports:
      - ${PG_PORT:-5432}:5432
    restart: always             
    volumes:
        - ${PG_DATA:-./postgresql}:/var/lib/postgresql/data
        
