name: GitHub Actions Example
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Echo event trigger
        run: echo "The job was automatically triggered by a ${{github.event_name}} event."