name: GitHub Actions Example
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out source code 
        run: actions/checkout@v4
      - name: setup python environment
        uses: actions/setup-python@v5
          with:
            python-version: '3.13'
      - name: check python version
        run: python --version