runs-on: self-hosted
name: GitHub Actions Example
on: [push]		
jobs:
  Explore-GitHub-Actions:
  runs-on: ubuntu-latest
     steps:
      run: echo " The job was automatically triggered by a ${{Github.event_name }} event."