name: GitHub Actions Example
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python:
          - 3.10.7
          - 3.12.7
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: check python version
        run: python --version