name: GitHub Actions Example
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python:
          - 3.12.7
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Install python version
        uses: gabrielfalcao/pyenv-action@v18
        with:
          default: "${{ matrix.python }}"
          command: pip install -U pip
      - name: check python version
        run: python --version